In [1]:
# Hyper parameter Tuning (GridSearchCV)

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x:iris.target_names[x])

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

In [26]:
from sklearn import svm
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [27]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),
               iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [31]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),
               iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [32]:
cross_val_score(svm.SVC(kernel='rbf',C=40,gamma='auto'),
               iris.data,iris.target,cv=5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

In [36]:
kernels = ['rbf', 'linear']
C = [1,10,20]

avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),
                                   iris.data,iris.target,cv=5)
        
        avg_scores[kval + '-' + str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf-1': 0.9800000000000001,
 'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9666666666666668,
 'linear-1': 0.9800000000000001,
 'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666}

In [37]:
from sklearn.model_selection import GridSearchCV

In [39]:
clf = GridSearchCV(svm.SVC(gamma='auto'),
                  {'C': [1,10,20],
                  'kernel':['rbf','linear']},
                  cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00119987, 0.00059896, 0.00099888, 0.00100074, 0.00079999,
        0.00100203]),
 'std_fit_time': array([3.98326987e-04, 4.89045835e-04, 1.00701867e-06, 3.03682009e-06,
        3.99996225e-04, 1.36044909e-06]),
 'mean_score_time': array([0.00039845, 0.00080137, 0.00020013, 0.0001997 , 0.00019722,
        0.00039983]),
 'std_score_time': array([0.00048799, 0.00040069, 0.00040026, 0.0003994 , 0.00039444,
        0.00048969]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [42]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001200      0.000398         0.000398        0.000488       1   
1       0.000599      0.000489         0.000801        0.000401       1   
2       0.000999      0.000001         0.000200        0.000400      10   
3       0.001001      0.000003         0.000200        0.000399      10   
4       0.000800      0.000400         0.000197        0.000394      20   
5       0.001002      0.000001         0.000400        0.000490      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [46]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [47]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [49]:
clf.best_score_

0.9800000000000001

In [50]:
clf.best_score_

0.9800000000000001

In [57]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'),{
                       'C':[1,10,20],
                       'kernel':['rbf','linear']
    }, cv=5,return_train_score=False, n_iter=2)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1       1          rbf         0.980000

In [58]:
# How to choose best model for a problem

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [60]:
model_params = {
    'svm': {
    'model': svm.SVC(gamma='auto'),
    'param': {
     'C': [1,10,20],
     'kernel': ['rbf','linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'param': {
            'n_estimators': [1,5,10]
        }
    },
    
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'param': {
            'C': [1,5,10]
        }
    }    
}

In [74]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['param'],cv=5,
                      return_train_score=False)
    clf.fit(iris.data,iris.target)
    
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_        
    })

scores

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.9533333333333334,
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}}]

In [76]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [77]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [78]:
from sklearn.datasets import load_digits
digits = load_digits()

In [79]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [80]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [81]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [92]:
len(X_train)

1437

In [93]:
len(y_train)

1437

In [94]:
from sklearn import svm
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.5305555555555556

In [95]:
from sklearn.model_selection import cross_val_score

In [96]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),
               iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [98]:
cross_val_score(svm.SVC(kernel='rbf',C=50,gamma='auto'),
               iris.data,iris.target,cv=5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

In [99]:
kernels = ['rbf', 'linear']
C = [1,10,20]

avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),
                                   iris.data,iris.target,cv=5)
        
        avg_scores[kval + '-' + str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf-1': 0.9800000000000001,
 'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9666666666666668,
 'linear-1': 0.9800000000000001,
 'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666}

In [100]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    },
    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params': {}
    },
    'naive_bayes_multinomial': {
        'model': MultinomialNB(),
        'params': {}
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy'],
            
        }
    }     
}

In [101]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                   best_params
0                      svm    0.947697  {'C': 1, 'kernel': 'linear'}
1            random_forest    0.899322          {'n_estimators': 10}
2      logistic_regression    0.922114                      {'C': 1}
3     naive_bayes_gaussian    0.806928                            {}
4  naive_bayes_multinomial    0.870350                            {}
5            decision_tree    0.800802      {'criterion': 'entropy'}

In [ ]:
# L1 and L2 Regularization | Lasso, Ridge Regression

In [177]:
dataset = pd.read_csv(r'C:\Users\prafulla.kamble\Downloads\0PRK\ML\CodeBasicsRepo\ML\16_regularization\Melbourne_housing_FULL.csv')
dataset.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [178]:
dataset.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [179]:
dataset.shape

(34857, 21)

In [180]:
columns_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'Price',
                  'SellerG', 'Regionname', 'Distance', 
                  'Propertycount','CouncilArea','Bedroom2', 
                  'Bathroom', 'Car', 'Landsize', 'BuildingArea',]
columns_to_use = dataset[columns_to_use]
dataset.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [181]:
len(dataset.columns)

21

In [182]:
dataset.shape

(34857, 21)

In [183]:
dataset.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [184]:
counts_to_fill_zero = ['Propertycount','Distance','Bedroom2',
                       'Bathroom','Car']

In [185]:
dataset[counts_to_fill_zero] = dataset[counts_to_fill_zero].fillna(0)
dataset.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             0
Postcode             1
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        0
dtype: int64

In [186]:
dataset['Landsize'] = dataset['Landsize'].fillna(dataset.Landsize.mean())
dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [187]:
dataset.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             0
Postcode             1
Bedroom2             0
Bathroom             0
Car                  0
Landsize             0
BuildingArea         0
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        0
dtype: int64

In [188]:
dataset= dataset.drop(dataset[['YearBuilt','Address','Postcode',
                              'Date','Lattitude','Longtitude']],
                      axis='columns')
dataset

Suburb  Rooms Type      Price Method        SellerG  Distance  \
0      Abbotsford      2    h        NaN     SS         Jellis       2.5   
1      Abbotsford      2    h  1480000.0      S         Biggin       2.5   
2      Abbotsford      2    h  1035000.0      S         Biggin       2.5   
3      Abbotsford      3    u        NaN     VB         Rounds       2.5   
4      Abbotsford      3    h  1465000.0     SP         Biggin       2.5   
...           ...    ...  ...        ...    ...            ...       ...   
34852  Yarraville      4    h  1480000.0     PI            Jas       6.3   
34853  Yarraville      2    h   888000.0     SP        Sweeney       6.3   
34854  Yarraville      2    t   705000.0      S            Jas       6.3   
34855  Yarraville      3    h  1140000.0     SP  hockingstuart       6.3   
34856  Yarraville      2    h  1020000.0     PI             RW       6.3   

       Bedroom2  Bathroom  Car    Landsize  BuildingArea  \
0           2.0       1.0  1.0  126.000000      160.2564   
1           2.0       1.0  1.0  202.000000      160.2564   
2           2.0       1.0  0.0  156.000000       79.0000   
3           3.0       2.0  1.0    0.000000      160.2564   
4           3.0       2.0  0.0  134.000000      150.0000   
...         ...       ...  ...         ...           ...   
34852       4.0       1.0  3.0  593.000000      160.2564   
34853       2.0       2.0  1.0   98.000000      104.0000   
34854       2.0       1.0  2.0  220.000000      120.0000   
34855       0.0       0.0  0.0  593.598993      160.2564   
34856       2.0       1.0  0.0  250.000000      103.0000   

                    CouncilArea             Regionname  Propertycount  
0            Yarra City Council  Northern Metropolitan         4019.0  
1            Yarra City Council  Northern Metropolitan         4019.0  
2            Yarra City Council  Northern Metropolitan         4019.0  
3            Yarra City Council  Northern Metropolitan         4019.0  
4            Yarra City Council  Northern Metropolitan         4019.0  
...                         ...                    ...            ...  
34852  Maribyrnong City Council   Western Metropolitan         6543.0  
34853  Maribyrnong City Council   Western Metropolitan         6543.0  
34854  Maribyrnong City Council   Western Metropolitan         6543.0  
34855  Maribyrnong City Council   Western Metropolitan         6543.0  
34856  Maribyrnong City Council   Western Metropolitan         6543.0  

[34857 rows x 15 columns]

In [189]:
dataset.dropna(inplace=True)
dataset

Suburb  Rooms Type      Price Method        SellerG  Distance  \
1      Abbotsford      2    h  1480000.0      S         Biggin       2.5   
2      Abbotsford      2    h  1035000.0      S         Biggin       2.5   
4      Abbotsford      3    h  1465000.0     SP         Biggin       2.5   
5      Abbotsford      3    h   850000.0     PI         Biggin       2.5   
6      Abbotsford      4    h  1600000.0     VB         Nelson       2.5   
...           ...    ...  ...        ...    ...            ...       ...   
34852  Yarraville      4    h  1480000.0     PI            Jas       6.3   
34853  Yarraville      2    h   888000.0     SP        Sweeney       6.3   
34854  Yarraville      2    t   705000.0      S            Jas       6.3   
34855  Yarraville      3    h  1140000.0     SP  hockingstuart       6.3   
34856  Yarraville      2    h  1020000.0     PI             RW       6.3   

       Bedroom2  Bathroom  Car    Landsize  BuildingArea  \
1           2.0       1.0  1.0  202.000000      160.2564   
2           2.0       1.0  0.0  156.000000       79.0000   
4           3.0       2.0  0.0  134.000000      150.0000   
5           3.0       2.0  1.0   94.000000      160.2564   
6           3.0       1.0  2.0  120.000000      142.0000   
...         ...       ...  ...         ...           ...   
34852       4.0       1.0  3.0  593.000000      160.2564   
34853       2.0       2.0  1.0   98.000000      104.0000   
34854       2.0       1.0  2.0  220.000000      120.0000   
34855       0.0       0.0  0.0  593.598993      160.2564   
34856       2.0       1.0  0.0  250.000000      103.0000   

                    CouncilArea             Regionname  Propertycount  
1            Yarra City Council  Northern Metropolitan         4019.0  
2            Yarra City Council  Northern Metropolitan         4019.0  
4            Yarra City Council  Northern Metropolitan         4019.0  
5            Yarra City Council  Northern Metropolitan         4019.0  
6            Yarra City Council  Northern Metropolitan         4019.0  
...                         ...                    ...            ...  
34852  Maribyrnong City Council   Western Metropolitan         6543.0  
34853  Maribyrnong City Council   Western Metropolitan         6543.0  
34854  Maribyrnong City Council   Western Metropolitan         6543.0  
34855  Maribyrnong City Council   Western Metropolitan         6543.0  
34856  Maribyrnong City Council   Western Metropolitan         6543.0  

[27244 rows x 15 columns]

In [212]:
dataset.isna().sum()

Rooms                                    0
Price                                    0
Distance                                 0
Bedroom2                                 0
Bathroom                                 0
                                        ..
Regionname_Northern Victoria             0
Regionname_South-Eastern Metropolitan    0
Regionname_Southern Metropolitan         0
Regionname_Western Metropolitan          0
Regionname_Western Victoria              0
Length: 745, dtype: int64

In [213]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset.head()

Rooms      Price  Distance  Bedroom2  Bathroom  Car  Landsize  \
1      2  1480000.0       2.5       2.0       1.0  1.0     202.0   
2      2  1035000.0       2.5       2.0       1.0  0.0     156.0   
4      3  1465000.0       2.5       3.0       2.0  0.0     134.0   
5      3   850000.0       2.5       3.0       2.0  1.0      94.0   
6      4  1600000.0       2.5       3.0       1.0  2.0     120.0   

   BuildingArea  Propertycount  Suburb_Aberfeldie  ...  \
1      160.2564         4019.0                  0  ...   
2       79.0000         4019.0                  0  ...   
4      150.0000         4019.0                  0  ...   
5      160.2564         4019.0                  0  ...   
6      142.0000         4019.0                  0  ...   

   CouncilArea_Wyndham City Council  CouncilArea_Yarra City Council  \
1                                 0                               1   
2                                 0                               1   
4                                 0                               1   
5                                 0                               1   
6                                 0                               1   

   CouncilArea_Yarra Ranges Shire Council  Regionname_Eastern Victoria  \
1                                       0                            0   
2                                       0                            0   
4                                       0                            0   
5                                       0                            0   
6                                       0                            0   

   Regionname_Northern Metropolitan  Regionname_Northern Victoria  \
1                                 1                             0   
2                                 1                             0   
4                                 1                             0   
5                                 1                             0   
6                                 1                             0   

   Regionname_South-Eastern Metropolitan  Regionname_Southern Metropolitan  \
1                                      0                                 0   
2                                      0                                 0   
4                                      0                                 0   
5                                      0                                 0   
6                                      0                                 0   

   Regionname_Western Metropolitan  Regionname_Western Victoria  
1                                0                            0  
2                                0                            0  
4                                0                            0  
5                                0                            0  
6                                0                            0  

[5 rows x 745 columns]

In [214]:
X = dataset.drop('Price',axis=1)
y = dataset['Price']

In [243]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=2)

In [244]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [245]:
model.score(X_test,y_test)

0.1385368316161545

In [246]:
model.score(X_train,y_train)

0.6827792395792723

In [247]:
from sklearn import linear_model

In [248]:
lasso_reg = linear_model.Lasso(alpha=50,max_iter=100,tol=0.1)
lasso_reg.fit(X_train,y_train)

C:\Users\prafulla.kamble\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1329087287481363.0, tolerance: 796258688308222.5
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=50, max_iter=100, tol=0.1)

In [249]:
lasso_reg.score(X_test,y_test)

0.6637669697137102

In [250]:
lasso_reg.score(X_train,y_train)

0.6767356948457683

In [251]:
# L2 Regularization - Ridge

In [252]:
from sklearn.linear_model import Ridge

In [253]:
ridge_reg = Ridge(alpha=50,max_iter=100,tol=0.1)
ridge_reg.fit(X_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [255]:
ridge_reg.score(X_test,y_test)

0.6670848945194959

In [257]:
ridge_reg.score(X_train,y_train)

0.6622376739684328